login_cred_profile          = "Shared"
switch_role_cred_profile    = "AI-Self-Help"
iam_group_name              = "AI-Self-Help-Content-Creators"
assume_role_policy_name     = "assumerole-ai-chat-content-creators"
assumed_role                = "ai-chat-content-creator-role-assumed"