login_cred_profile       = "Shared"
switch_role_cred_profile = "CA-Prod"
iam_group_name           = "Canada-Network"
assume_role_policy_name  = "canada-network-readonly"
assumed_role             = "canada-network-role-assumed"