login_cred_profile       = "Shared"
switch_role_cred_profile = "US-Prod"
iam_group_name           = "AI-SelfHelp-Lex-Admin"
assume_role_policy_name  = "ai-self-help-lex-admin"
assumed_role             = "ai-self-help-lex-admin-role-assumed"