login_cred_profile       = "Shared"
switch_role_cred_profile = "US-Prod"
iam_user_name            = "terraform_ci_for_bitbucket"
assume_role_policy_name  = "AssumeTerraformBitbucketRole"
assumed_role             = "terraform-ci-for-bitbucket-role-assumed"